sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: W09cE0OgUk8NkuKnHNK/urwHhffSB0IR0aFD1/yJQJZhTLPdWxqR6ioVpT3Hp+ChaJu3YrIq9Shb8X58WRzJm4HyvvHJBlioiqX6JWaEUPxjmzkLgjuM/h1oF6jAyX4VDdAdUNiuD1fi+NgSwZG60ptjQ3oVbvHYVxp1BFIrBbfIFDKhfmYy8M4LqlR12mUYz2Hk7xmW/EUGQgAxbOiy+hodhl9nocF/iGKt4c9ODc2Cpmwsl5qU9t9w3EHKgH0J617jNhZrra4EbELkmFU+jxjQirjGp72+V46h2gFuLdyE1DZQU5elAV7u4hEaaPsIMyf7Vl1pe5gnSuG+xhSTr9hOzFki7n77qVJ0+Hp5wZXn+Pvn2mfCvKZqRtTNWyJSYVg7Dww0k9ZJo63Oz9catCOYy05kaxaxVf3AFuaLkzhFy/4bAkcXHVsmXAmgO6c+iypggxHZuZImvAhD8PzJg3ovsjsKojbdySmE/4A9R8eFbWvZ1rKWusR5Y3SDvx7ncPpXl0jAHn1lHEdUwjiOr2v3KPU0xoyKjSacpCrLrUJXboHLcI1rWbtW8aF8ZFzL5ClKBQBIzJIlfIERLeBppJX1t/s6zb5HT/WBHqNPfQqtoY7a4L8oePB1/JvMKoJGkbaf6LABdf6UuB4QYfkcDNuEYyQzaBlNZeQIc52rlpU=
  - secure: H2HOJWWI890CA7HCnB3+qvCB3vnC1vT8iV5qPJVO6AIC68pxySUlqPRvjBba4Re+iYSZeMevzNC2VxBwCuzjNfVsUVy61Kt3o5OZVmb9hb+5mboXr9M+pgCgBDipj9K7oXww3bFLh1EOwGFhreLuhkUo0gYLIV3i2TIj2AiNoHVxMJ7LaxV6mRPyhmpZJjT71et39uUhQx+agNR8HNOUqc8157KSgfIdgTa5DvyByOIJSti1vGc/9lsHtKp23mw3ureZfvjsGsUAjpTNE8sBUSxkW3bI0unWKRiWy6AUzazTk6NAzY1XIeMRnYjqluwQjhUIZ5nPpvsP7Mn16gOD8mFx0KXhN/pxc77E+klWS5mQ1fjkck6XA81nYLSI87vL0F1MslkxA98h/gfU3zrkswJSO5OwHZgXLGQwxQYz1Srq9uielj7HnkfMzwCmlsrOV97/Jy2kfAs1qTiLFkN4yrVgXCdikRDOZ90g/LuAVzX+Yijj/UdFkJ1iU3/RNpvrZYsFvTelwmJeT/0/hXlq/+Aiz+zCtHFQtoeqIx2fnoSwgMLWavK6KZg3Ov4tfRrXIOEb/OEEM/EwteaaRjQbf84OXQ2FC/mLLmrpgj3SdrmNgiatxoMJgk8cakK+OWMvYJ+wQfE0kapTjAYo1X4fgs4pjgfZHKwqI7jp9OJLtsI=
  - secure: YWjspEcOxNHt4dDwMxd2/OruqwPRigoIAq1ChBhQHOEkEV0grzrlqawM1bCe9Q7Up7bam7+cA/CPRXG5vQoBhHEg4krSJ3e7GIq9WLCnhTu4A4TYpKrBTjHIt2FBLZC9upvZIVr+ocgd3V/C/WgHW+Ty8bjH0umgm0bTLEQqqt4jjAgorgKZbvI9AIHXCFfOre1XhuDl8mZr5PfTXo16WiterGLdjfd5yQloUvSR3zQVSlyFJsnU7sQKciw9Wd8ww0ps49t9DCG9bmWa9EG0BHro38nfRKcR0M1DFWWbNiPSnfwppevrbH5Qrm12vh4t2iwcIP5pkkOK2jYj9lHiJQDH74c91yvuaKTEn1PYOtxnfkzDNrqRScedCLCQTao1dImHKqcEky7cdQ03s8M2swOmOVgHN0ld26MYqFbq+XW4UxQ8AoXLJ8ER4kPixwUlND9xNYltGYWpfXas1HLZ4PecqajKkRsDitsLdBqVnkrCettpUw8KNt3geq4OBHzG0Saar3UxH6a12sv/1Gv8twA2Uj0vwilP4Df2HSyMbK0q4S04P8M4ShLM3AG1xoiH24xevbyDdttpSJgjsPE54IntDTCm1FXY2S3ZF1EQfLW+UWcsMPHRjVz1zO/cV3vh/+ltdONh6KnsAeG6ixNSDGydDAG2eAFJhhDGRu228hI=
  - secure: TaaOvhaz1ngPATnxdNBIVLYBYHsZy9sICD9cnt5MimQTqSprX/l2nRqXV4u1UtzNtLwMna2cjewxzRKQjrj06gEUsLyZEjcOrwBdVuPHt96CtJOPgRz1Smsq/bwlQHvZEsB9LAKV7rUxYYtb2U09Ij3y7WYZrM7I0rjC5GYacdyMfG0ocsQtyfVxh5f+FIfZo48QKkkq21J+UucdrqIBB2nIzyUDLPiH2bF74LiMLXwbCytxdk3SZtCM3H3QgJ2RaSUxlXPDYIlzO22VxSLSlUF7sdx5L5dKEGta3HJatmFUCy8+NdJPJZMkIfQfWBzh0AQgxPXar8v4VJCLvavbYwyaU0kc8JsaTImVJDyPjV5tGVtOZdzEjn0kM0xOdALGVVyOxum3wbOBynI2MWaj+v76ZDv0h+bmgEukvoBTO0IXsuYw2S+zwkDE4n4SvjZBWSFe0EPiobtPyLFU4f2/qBB5g2eQ3W4bXd2V+gcSmy8XE3iC3M7yb3clywIL31sXMonGKa6fPaazhqM5tweDsI6ZZCErtsQOAEKExnVSf9xGx6YxICTzqjazrOUiZtq5CQXwRjP64vHHK05ueS1pEPlkM9baFoXKJOo/Eti9lvpzmQdUcszryHA+GS9nzz7kAjox2w5eXaXnYLky5YjMOb+7zUSPZh0IH1eeGfN1u0Q=
  - secure: bmxUOGQ+qGRZquMIdNg5FoeMY5CftFYF1yb4wnUsYB+mZ+PDcAfiCx0T1JOH83I99nmOuIK8YwSUPVEIES2r79tH4u1qjuEkAVXEdR5sJ43m/QULMXqoABO3sg6gTJ0VUeoNMc3MycUg1n/0bNXJpiKl6fawyzA8Hu2j7MZRgHE79v+48/cmqrre/shLw+EVTqgzggvEW6Je9M+a2FhPMSdPfijB8iptzI25TKDreZK4NGp4h2bgwy4RV7m0SE9LzUp2G/wX3g+JfNRAI8KtmYbP1qzawOVdprmCZJobLCueq4fJS/M7dsL0qBeKs1cEe4Sn7rdVZpqs7YuY3xRtO5rHyPoP20VtmLmjLZGoTKoCRXPC0Taj7+23puwPEUvRYvS3+GMN6imh7Fv2QFD+gyEeMpj5XcB5mFEIYphtRpkb3shi7USu95JbgNSxpwkeOCL2Bfq91HtvY2hLgpTLXOCT/wAdbyQtMNaxm2Qcm4fvqiuj+msGklzmd/GYOpZ1b+wUS/627CbO5mJbhHFnNnPxRb2PD+bef4XvZxaCfh3Jtk11KNXZPFeMv14fVmWdcaPiJIr68WQO3R3wA28Mv0kz1CU7XdIDCZpdHvHQtjqnfhwCQt8bFLcAIt/rDoSExkOpSkrCZeQaJqWNbdCc0/Hmr9N+82uVIuSVMuHPadw=
